<br>
	<br>
		<p><span style="font-family: arial,helvetica,sans-serif; font-size: 16pt; color: #0064c8; line-height: 120%;">Dodatna zarada</span>
		</p>
		<br>
<div class="content-zarada">
<br>
<br>
<img src="<?php echo base_url(); ?>includes/images/posao.png" style="margin-left:20px;">
<table style="width: 701px; height: 79px;" _mce_new="1" border="0">
    <tbody>
        <tr>
            <td style="text-align: center; border-color: #4a4a4a; border-width: 1px; background-color: #d7ecfe; border-style: solid;" colspan="2">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<span style="font-family: arial,helvetica,sans-serif; font-size: 14pt;">&nbsp;<strong><span style="color: #4a4a4a; font-size: 12pt;"> <br />OBJAŠNJENJE TABLICE ZA SVE DJELATNIKE, ZASTUPNIKE, POVJERENIKE I ČLANOVE </span></strong></span><br /><strong><span style="font-family: arial,helvetica,sans-serif; font-size: 12pt; color: #4a4a4a;"><br /></span></strong><span style="font-family: arial,helvetica,sans-serif; font-size: 12pt; color: #4a4a4a;">koji su uključeni u provizijsku stopu</span></td>
        </tr>
    </tbody>
</table>
<br /><br /><br /><br /><br /><br />
<table style="border-color: #4a4a4a; border-style: solid; border-width: 0px; width: 701px; height: 924px;" _mce_new="1" border="0">
    <tbody>
        <tr>
            <td style="text-align: center; border-color: #4a4a4a; border-width: 0px 0px 1px; border-style: solid;" rowspan="7">&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp;&nbsp; <br _mce_bogus="1" /><br _mce_bogus="1" /><br _mce_bogus="1" /><br _mce_bogus="1" /><br _mce_bogus="1" /><br _mce_bogus="1" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;</td>
            <td style="border-color: #4a4a4a; border-style: solid; border-width: 0px 0px 1px;" rowspan="2"><span style="font-family: arial,helvetica,sans-serif;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br /><br /><img style="display: block; margin-left: auto; margin-right: auto;" alt="group-02" src="<?php echo base_url(); ?>includes/images/group-02.png" height="100" width="100" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <br /></span></td>
            <td style="border-color: #4a4a4a; border-style: solid; border-width: 1px 0px 0px 1px; background-color: #ffffff; text-align: center;"><span style="color: #ffffff; font-family: arial,helvetica,sans-serif;">&nbsp;<span style="font-size: 12pt;"><br />&nbsp;&nbsp; <br />&nbsp; <span style="color: #4a4a4a;"><strong>DJELATNIK&nbsp;</strong> &nbsp;</span> &nbsp; </span></span></td>
            <td style="border-color: #4a4a4a; border-style: solid; border-width: 1px 0px 0px 1px; background-color: #e7e7e8; text-align: center;"><span style="color: #4a4a4a;">&nbsp;&nbsp;&nbsp; <br /><span style="font-size: 12pt; font-family: arial,helvetica,sans-serif;"><br /><strong>ZASTUPNIK</strong></span> </span></td>
            <td style="border-color: #4a4a4a; border-style: solid; border-width: 1px 1px 0px; text-align: center; background-color: #ffffff;"><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br /><br /><strong>POVJERENIK</strong> &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></td>
            <td style="background-color: #e7e7e8; border-color: #000000; border-width: 1px 1px 0px 0px; border-style: solid; text-align: center;" align="center" valign="middle"><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">&nbsp; <br /><br /><strong>ČLAN&nbsp;&nbsp; </strong></span></td>
        </tr>
        <tr>
            <td style="border-color: #4a4a4a; border-style: solid; border-width: 1px 0px 1px 1px; background-color: #ffffff; text-align: center;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br /><strong>Zaposlena osoba</strong></span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">Plaćanje u obliku dohotka</span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">Puno ili nepuno <br />radno vrijeme<br /></span></td>
            <td style="border-color: #4a4a4a; border-style: solid; border-width: 1px 0px 1px 1px; background-color: #e7e7e8; text-align: center;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><strong>Zaposlena osoba</strong></span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">Plaćanje u obliku dohotka</span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">Puno ili nepuno <br />radno vrijeme</span></td>
            <td style="border-color: #4a4a4a; border-style: solid; border-width: 1px; text-align: center; background-color: #ffffff;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br /><strong>Honorarni posao</strong></span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">Plaćanje u obliku <br />provizije<br /></span></td>
            <td style="text-align: center; border-color: #4a4a4a; border-width: 1px 1px 1px 0px; border-style: solid; background-color: #e7e7e8;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br /><strong>Dodatna zarada</strong></span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">Plaćanje u obliku BOD-ova<br /></span></td>
        </tr>
        <tr>
            <td style="border-color: #4a4a4a; border-style: solid; border-width: 0px 0px 1px 1px; background-color: #d7ecfe;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">&nbsp;&nbsp; <br />&nbsp;&nbsp; <br />&nbsp;&nbsp; DOHODAK<br /><br /></span></td>
            <td style="border-color: #4a4a4a; border-style: solid; border-width: 0px 0px 1px 1px; text-align: center; background-color: #ffffff;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />Minimalni fiksni</span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">+</span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">varijabilni<br /></span></td>
            <td style="border-color: #4a4a4a; border-style: solid; border-width: 0px 0px 1px 1px; text-align: center; background-color: #e7e7e8;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />Dogovoreni fiksni</span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">+</span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">varijabilni<br /></span></td>
            <td style="border-color: #4a4a4a; border-style: solid; border-width: 0px 1px 1px; text-align: center; background-color: #ffffff;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />Po učinku neto</span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">+</span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">doprinosi<br /></span></td>
            <td style="border-color: #4a4a4a; border-style: solid; border-width: 0px 1px 1px 0px; text-align: center; background-color: #e7e7e8;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />Kontakt za <br />novi posao</span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">u obliku poklona<br /></span></td>
        </tr>
        <tr>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #d7ecfe;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />&nbsp;&nbsp; DOKAZ UPLATE</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />Nakon vidljive uplate</span><br _mce_bogus="1" /><br _mce_bogus="1" /></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #e7e7e8;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">Nakon vidljive uplate</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">Nakon vidljive uplate</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px 0px; border-style: solid; text-align: center; background-color: #e7e7e8;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">Nakon vidljive uplate</span></td>
        </tr>
        <tr>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #d7ecfe; text-align: justify;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">&nbsp;&nbsp; <br /><br />&nbsp;&nbsp; ISPLATA</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br /><br />Sa isplatom plače</span><br _mce_bogus="1" /><br _mce_bogus="1" /></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #e7e7e8;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">Sa isplatom plače</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />Do 15og u tekućem mjesecu</span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">za protekli mjesec</span><br _mce_bogus="1" /><br _mce_bogus="1" /></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px 0px; border-style: solid; text-align: center; background-color: #e7e7e8;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">Do 15og u tekućem mjesecu</span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">za protekli mjesec</span></td>
        </tr>
        <tr>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #d7ecfe; text-align: left;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">&nbsp; <br />&nbsp;&nbsp; PROVIZIJA U %-tku &nbsp; <span style="color: #d7ecfe;">%-tku</span><br /> </span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br /><span style="font-size: 12pt;">Dogovor</span></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #e7e7e8;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br /><span style="font-size: 12pt;">%</span></span><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"></span><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><span style="font-size: 12pt;">%</span></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px 0px; border-style: solid; text-align: center; background-color: #e7e7e8;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><span style="font-size: 12pt;">%</span></span></td>
        </tr>
        <tr>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #d7ecfe; text-align: left;"><span style="font-family: arial,helvetica,sans-serif;"><span style="font-size: 10pt; color: #4a4a4a;">&nbsp; <br />&nbsp;&nbsp; IZNOS OD KOJEG<br />&nbsp;&nbsp; SE OBRAČUNAVA<br />&nbsp;&nbsp; PROVIZIJA <br /></span></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><span style="font-family: arial,helvetica,sans-serif; font-size: 10pt; color: #4a4a4a;"><br />Račun - uplaćeni</span><br /><span style="font-family: arial,helvetica,sans-serif; font-size: 10pt; color: #4a4a4a;">iznos bez PDV-a</span><span style="font-family: arial,helvetica,sans-serif;"><br /></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #e7e7e8;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />Postotak koji se oduzima od računa</span><br /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">uplaćenog iznosa <br />bez PDV-a</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />Postotak koji se oduzima od <br />zastupničkog iznosa bez PDV-a</span><br _mce_bogus="1" /><br _mce_bogus="1" /></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px 0px; border-style: solid; text-align: center; background-color: #e7e7e8;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">Postotak koji se oduzima od <br />zastupničkog iznosa bez PDV-a</span></td>
        </tr>
        <tr>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center;"><strong><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />1<br /><br /></span></strong></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #b4dcfd;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><strong>&nbsp;&nbsp; <br />&nbsp;&nbsp; WebMediaWeb</strong></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><span style="font-size: 12pt;"><br />Dogovor</span></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #e7e7e8;"><span style="font-family: arial,helvetica,sans-serif; font-size: 12pt; color: #4a4a4a;"><br />75 % bruto</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />50 % bruto</span><br _mce_bogus="1" /><br _mce_bogus="1" /></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px 0px; border-style: solid; text-align: center; background-color: #e7e7e8;"><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />30% bruto</span><br _mce_bogus="1" /><br _mce_bogus="1" /></td>
        </tr>
        <tr>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center;"><strong><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />2<br /><br /></span></strong></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #b4dcfd;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">&nbsp;&nbsp; <br />&nbsp;&nbsp; <strong>MobiCash</strong></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #ffffff; text-align: center;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><span style="font-size: 12pt;">Dogovor</span></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #e7e7e8; text-align: center;"><br data-mce-bogus="1" /><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">75 % bruto</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px; border-style: solid; background-color: #ffffff; text-align: center;"><br data-mce-bogus="1" /><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">50 % bruto</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px 0px; border-style: solid; background-color: #e7e7e8; text-align: center;">&nbsp;<span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />30% bruto</span></td>
        </tr>
        <tr>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center;"><strong><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />3<br /><br /></span></strong></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #b4dcfd;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">&nbsp;&nbsp; <br />&nbsp;&nbsp; <strong>ScandiEuro</strong></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #ffffff; text-align: center;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><span style="font-size: 12pt;">Dogovor</span></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #e7e7e8;"><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />30 % bruto</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><br data-mce-bogus="1" /><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">50 % bruto</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px 0px; border-style: solid; text-align: center; background-color: #e7e7e8;"><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />30 % bruto</span></td>
        </tr>
        <tr>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center;"><strong><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />4<br /><br /></span></strong></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #b4dcfd;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">&nbsp;&nbsp; <br />&nbsp;&nbsp; <strong>ASEuro</strong></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #ffffff; text-align: center;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><span style="font-size: 12pt;">Dogovor</span></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #e7e7e8;"><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />10 % bruto</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><br data-mce-bogus="1" /><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">50 % bruto</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px 0px; border-style: solid; text-align: center; background-color: #e7e7e8;"><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />30% bruto</span></td>
        </tr>
        <tr>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center;"><strong><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />5<br /><br /></span></strong></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #b4dcfd;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">&nbsp;&nbsp; <br />&nbsp;&nbsp; <strong>CroatiaAveto</strong></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #ffffff; text-align: center;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><span style="font-size: 12pt;">Dogovor</span></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #e7e7e8;"><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />60 % bruto</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><br data-mce-bogus="1" /><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">50 % bruto</span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px 0px; border-style: solid; text-align: center; background-color: #e7e7e8;"><span style="font-size: 12pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />30% bruto</span></td>
        </tr>
        <tr>
            <td style="text-align: center; border-color: #000000; border-width: 0px 0px 1px 1px; border-style: solid;"><strong><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><br />6</span></strong></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #b4dcfd;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;">&nbsp;&nbsp;&nbsp; <br />&nbsp;&nbsp; <strong>MiranSan</strong></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; background-color: #ffffff; text-align: center;"><br data-mce-bogus="1" /><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><span style="font-size: 12pt;">Dogovor</span></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 0px 1px 1px; border-style: solid; text-align: center; background-color: #e7e7e8;"><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><span style="color: #0000ff;"><strong><br /><a target="_blank" href="http://miransan.com.hr/dodatna-zarada.html"><span style="color: #0000ff;">Vidi tablicu</span></a></strong></span></span><br _mce_bogus="1" /><br _mce_bogus="1" /></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px; border-style: solid; text-align: center; background-color: #ffffff;"><a target="_blank" href="http://miransan.com.hr/dodatna-zarada.html"><br data-mce-bogus="1" /></a><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><span style="color: #0000ff;"><strong><a target="_blank" href="http://miransan.com.hr/dodatna-zarada.html"><span style="color: #0000ff;">Vidi tablicu</span></a></strong></span></span></td>
            <td style="border-color: #4a4a4a; border-width: 0px 1px 1px 0px; border-style: solid; text-align: center; background-color: #e7e7e8;"><a target="_blank" href="http://miransan.com.hr/dodatna-zarada.html"><br data-mce-bogus="1" /></a><span style="font-size: 10pt; color: #4a4a4a; font-family: arial,helvetica,sans-serif;"><span style="color: #0000ff;"><strong><a target="_blank" href="http://miransan.com.hr/dodatna-zarada.html"><span style="color: #0000ff;">Vidi tablicu</span></a></strong></span></span></td>
        </tr>
    </tbody>
</table>
<br>
</div>