<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="dnevni_boravak" <?php if (isset($detalji_smjestajne_jedinice['dnevni_boravak'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_dnevni_boravak'); ?> </span> </p> 
<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="pogled" <?php if (isset($detalji_smjestajne_jedinice['pogled'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_pogled'); ?> </span> </p> 
<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="internet" <?php if (isset($detalji_smjestajne_jedinice['internet'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_internet'); ?> </span> </p>
<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="hladovina" <?php if (isset($detalji_smjestajne_jedinice['hladovina'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_hladovina'); ?> </span> </p>
<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="spavace_sobe" <?php if (isset($detalji_smjestajne_jedinice['spavace_sobe'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_spavace_sobe'); ?> </span> </p>
<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="svaka_soba_balkon" <?php if (isset($detalji_smjestajne_jedinice['svaka_soba_balkon'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_svaka_soba_balkon'); ?> </span> </p>
<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="svaka_soba_wc" <?php if (isset($detalji_smjestajne_jedinice['svaka_soba_wc'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_svaka_soba_wc'); ?> </span> </p>
<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="svaka_soba_satelit" <?php if (isset($detalji_smjestajne_jedinice['svaka_soba_satelit'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_svaka_soba_satelit'); ?> </span> </p>
<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="svaka_soba_pogled" <?php if (isset($detalji_smjestajne_jedinice['svaka_soba_pogled'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_svaka_soba_pogled'); ?> </span> </p>
<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="terasa" <?php if (isset($detalji_smjestajne_jedinice['terasa'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_terasa'); ?> </span> </p>
<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="klima" <?php if (isset($detalji_smjestajne_jedinice['klima'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_klima'); ?> </span> </p>
<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="parking" <?php if (isset($detalji_smjestajne_jedinice['parking'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_parking'); ?> </span> </p>
<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="travnjak" <?php if (isset($detalji_smjestajne_jedinice['travnjak'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_travnjak'); ?> </span> </p>
<p> <input class="type-checkbox" type="checkbox" name="detalji_smjestajne_jedinice[]" value="bazen" <?php if (isset($detalji_smjestajne_jedinice['bazen'])) { echo 'checked'; } ?>/> <span> <?php echo lang('uredi_oglas_bazen'); ?> </span> </p>

